### ISSUE TITLE
Unable to be used in Platform IO

### ISSUE THREAD

**Issue by jorgie0** [ricaun/ArduinoUniqueID#3]
If PlatformIO is used as the compiler for an Arduino sketch the 2nd time the include file is used it causes a compilation issue.
`expected ')' before '.' token` Line 51

This is not seen under Arduino IDE as it creates a single source code file before it compiles.

**Comment by ricaun** [comment]
Hello,
What do you mean the second time?!
I tested on PlatformIO and works fine... 
Are you using AVR, SAM, SAMD, STM32, or ESP?
Can you share the code?
Thanks.

**Comment by jorgie0** [comment]
Hi,
My apologies attempting to reproduce using a small example proved me wrong.
Something in another *.h file is causing the problem which I will now investigate.
