### ISSUE TITLE
you can keep memory

### ISSUE THREAD

**Issue by zhekaus** [ricaun/ArduinoUniqueID#9]
`extern ArduinoUniqueID _UniqueID;` wastes RAM.
Usually, you need to check ID just once. And no need to have it globally.
Please, fix it.

**Comment by ricaun** [comment]
Hello, I design this way for these reasons: 

* Some microcontrollers methods to read serial unique id is slow 
* Some libraries use UniqueID on loop
* Need to be simple to use

I think is not a good idea to change the library to gain some RAM, this change could break some codes that use UniqueID more the once.

See yaa!
